# Generated by Django 2.1.3 on 2018-11-21 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grocery',
            old_name='created_date',
            new_name='bought_date',
        ),
        migrations.AlterField(
            model_name='grocery',
            name='item',
            field=models.CharField(max_length=100),
        ),
    ]
