# Generated by Django 2.1.3 on 2018-12-03 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0005_auto_20181204_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piggytopup',
            name='reason',
            field=models.CharField(max_length=300),
        ),
    ]
